### PR TITLE
chore: add artifacts for tree depth 1 - 32

### PR DESCRIPTION
**Pull request by vplasencia**
## Description

Semaphore v4 will support tree depth from 1 - 32.

### CODE REVIEW

**Comment by cedoor** [comment]
Could you update the version of the package?

**Comment by vplasencia** [comment]
@cedoor done 👍

**Comment by sripwoud** [comment]
I am confused, haven't we already added these artifacts in #32?

**Comment by vplasencia** [comment]
Hey @sripwoud!

> I am confused, haven't we already added these artifacts

Kind of. We were missing tree depth 1.

**Comment by sripwoud** [comment]
So shouldn't this PR add only `semaphore-1.zkey`, `semaphore-1.wasm`?

**Comment by vplasencia** [comment]
> So shouldn't this PR add only semaphore-1.zkey, semaphore-1.wasm?

I had to generate other zk artifacts needed for the ceremony and also update some keys in the Semaphore repo. It was easier to update everything to make sure that everything would work fine because it was generated at the same time and have the same files.

**Review by cedoor — APPROVED** [review]

**Review by sripwoud — APPROVED** [review]
utACK

**Pull request merged**
