### PR TITLE
docs: add tdd about snark artifacts management and distribution solution

### PR DESCRIPTION
**Pull request by sripwoud**
This document stemmed from discussions I had with @cedoor while working on refactoring how snark artifacts are managed/fetched in [zk-kit](https://github.com/privacy-scaling-explorations/zk-kit) (see https://github.com/privacy-scaling-explorations/zk-kit/pull/240)

See #1

### CODE REVIEW

**Comment by sripwoud** [comment]
@cedoor @AtHeartEngineer tagging you first here, hoping you can share this in your circles with people who might need/be interested in this.

**Comment by cedoor** [comment]
@artwyman tagging you here as this started from a private discussion we had a few weeks ago. Your input would be very appreciated. I imagine this work will be very useful for Zupass as well.

**Review by cedoor — COMMENTED** [review]
Looks great!

**Review by cedoor — APPROVED** [review]

**Comment by glamperd** [comment]
Yes, automation is feasible. We can then think about how best to establish the full chain of trust - from github code to all the artifacts.

**Pull request merged**
