### PR TITLE
chore: add semaphore artifacts

### PR DESCRIPTION
**Pull request by vplasencia**
## Description

- Since the Semaphore v4 circuit changed, the zk artifacts were updated. 

- More tree depth will now be supported, from 2 to 32. 

**Note**: This PR should be merged after the Semaphore repo is updated to support the circuit changes as well.

## Related Issue(s)

Re https://github.com/semaphore-protocol/semaphore/issues/778

### CODE REVIEW

**Comment by cedoor** [comment]
@sripwoud re changeset and versioning. Considering https://github.com/privacy-scaling-explorations/snark-artifacts/issues/14#issuecomment-2105154616, I guess we should bump version 4.0.0-beta for this package right?

**Comment by sripwoud** [comment]
@vplasencia Thanks for the PR.
With @cedoor we are still in the process of defining the best way to version those artifacts.
What do you guys think of 
https://github.com/privacy-scaling-explorations/snark-artifacts/issues/14#issuecomment-2106981820

If we agree on it, then this PR should set the version in `@zk-kit/semaphore-artifacts`  
https://github.com/privacy-scaling-explorations/snark-artifacts/blob/2ca667565384b9b6bcee705715e00e5d0023d75c/packages/semaphore/package.json#L5

to what we have in `@semaphore-protocol/circuits`
https://github.com/semaphore-protocol/semaphore/blob/47bfebd4ed4b38ee0c19fff67849380ee79ea3f1/packages/circuits/package.json#L3

and mention `@semaphore-protocol/circuits` in the `@zk-kit/semaphore-artifacts` description
https://github.com/privacy-scaling-explorations/snark-artifacts/blob/2ca667565384b9b6bcee705715e00e5d0023d75c/packages/semaphore/package.json#L3

**Review by sripwoud — CHANGES_REQUESTED** [review]
@vplasencia Thanks for the PR.
With @cedoor we are still in the process of defining the best way to version those artifacts.
What do you guys think of 
https://github.com/privacy-scaling-explorations/snark-artifacts/issues/14#issuecomment-2106981820

If we agree on it, then this PR should set the version in `@zk-kit/semaphore-artifacts`  
https://github.com/privacy-scaling-explorations/snark-artifacts/blob/2ca667565384b9b6bcee705715e00e5d0023d75c/packages/semaphore/package.json#L5

to what we have in `@semaphore-protocol/circuits`
https://github.com/semaphore-protocol/semaphore/blob/47bfebd4ed4b38ee0c19fff67849380ee79ea3f1/packages/circuits/package.json#L3

and mention `@semaphore-protocol/circuits` in the `@zk-kit/semaphore-artifacts` description
https://github.com/privacy-scaling-explorations/snark-artifacts/blob/2ca667565384b9b6bcee705715e00e5d0023d75c/packages/semaphore/package.json#L3

**Comment by sripwoud** [comment]
@vplasencia I assume you scripted the creation of these artifacts? Asking because of #33  :smile:

**Comment by vplasencia** [comment]
Hey @sripwoud 

Regarding this comment: https://github.com/privacy-scaling-explorations/snark-artifacts/pull/32#pullrequestreview-2052078554

I agree. Please, let me know when we all agree so that I can change those values. 

Regarding this comment: https://github.com/privacy-scaling-explorations/snark-artifacts/pull/32#issuecomment-2107011708

Yes, we have scripts for everything related to the artifacts. Here is the repo: https://github.com/vplasencia/semaphorev4-generate-zk-artifacts

There is one script to generate the files with the specific format for this repo: https://github.com/vplasencia/semaphorev4-generate-zk-artifacts/blob/main/scripts/getWasmZkeyFiles.ts

I was thinking about integrating those scripts into [circomkit](https://github.com/erhant/circomkit) (which is what Semaphore uses for circuits) or maybe create a plugin but a new tool adapted to this repo should work too. 

Let me know if I can help with the issue https://github.com/privacy-scaling-explorations/snark-artifacts/issues/33

**Comment by cedoor** [comment]
@vplasencia we agreed on keeping the same version of the circuit package if it exists. (in this case `@semaphore-protocol/circuits`), and update that link only when the circuit is updated.

A new `circuit` field needs also to be added to the `package.json` file, like here: https://github.com/privacy-scaling-explorations/snark-artifacts/blob/4023ed5a9c87c58de6b84475accdd30e8b4ff73c/packages/semaphore-identity/package.json#L5

**Comment by vplasencia** [comment]
Hey @cedoor! Then the version of these artifacts should be `4.0.0-beta.9` because it's the current version of the Semaphore circuit, right?

**Comment by vplasencia** [comment]
I just added the new circuit field. When the new Semaphore version is released, I can update the version here.

**Comment by cedoor** [comment]
@vplasencia Yes, 4.0.0-beta.9 is fine for now!

**Review by cedoor — APPROVED** [review]

**Comment by vplasencia** [comment]
@cedoor perfect, done 👍

**Comment by cedoor** [comment]
Great! Ready to be merged :)

**Pull request merged**
